### ISSUE TITLE
[Task]: Write tests to ensure examples are working

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/wallet.rs#1010]
### Task description

Currently, not all examples are running. This gives a window of opportunity to write tests to see if the bindings work correctly. And to experiment with a mocking framework.

### Requirements

Tests:
- [ ] Create Account Manager
- [ ] Create Account
- [ ] Generate Address
- [ ] Check Balance
- [ ] Send Transfer
- [ ] Backup
- [ ] Restore
- [ ] Events
- [ ] Logger

### Acceptance criteria

TBD

### Creation checklist

- [ ] I have assigned this task to the correct people
- [ ] I have added the most appropriate labels
- [ ] I have linked the correct milestone and/or project

**Comment by tuddman** [comment]
I am trying to run the examples, or rather use the examples as the basis for making an application that uses `wallet.rs`.

Now I'm getting this error:  `ClientError(Json(Error("missing field 'nodeinfo'", line: 1, column: 887)))`
when my application hits [this line](https://github.com/iotaledger/wallet.rs/blob/develop/examples/04_get_balance.rs#L19)

tracing back to [this JSON error in iota.rs?](https://github.com/iotaledger/iota.rs/blob/a884558653aa99b9a638a938d95e282bd78c9496/src/error.rs#L113)

➕ for having automated test coverage to ensure all of the examples continue to work.  It is what 'outsiders' rely on to use this library in building IOTA applications.
