### ISSUE TITLE
[Task]: Add logs for message_interface

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/wallet.rs#1026]
### Task description

Add logs for message_interface so all called methods can be seen
Also make sure that it doesn't leak secrets (mnemonics, passwords) in the provided values or in the response from generateMnemonic

### Requirements

- [ ] Log all message here https://github.com/iotaledger/wallet.rs/blob/48ef3f60fae7b2ea28aad52090d3256869043794/src/message_interface/message_handler.rs#L87
- [ ] For messages with secrets, only log their type/part of the payload without a secret

### Acceptance criteria

N/A

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
