### ISSUE TITLE
[Task]: Update sending flow / functions for Firefly requirments

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/wallet.rs#1035]
### Task description

As a requirement for the Firefly frontend, we would like the wallet.rs to be able to build a transaction payload and return the storage deposit amount before the user confirms the transaction. Therefore we require the development of some additional functions / bindings.

### Requirements

New functions and bindings for
- [ ] prepareTransaction - prepare a transaction object and calculate storage deposit
- [ ] signTransaction - sign transaction
- [ ] submitTransaction - submit / send transaction (maybe call this sendTransaction?)

### Acceptance criteria

Above requirements have been met.

### Creation checklist

- [ ] I have assigned this task to the correct people
- [ ] I have added the most appropriate labels
- [ ] I have linked the correct milestone and/or project

**Comment by Thoralf-M** [comment]
Related to https://github.com/iotaledger/wallet.rs/issues/948 (offline signing needs more changes)
