### ISSUE TITLE
Benchmark the sync and restore accounts functionality

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/wallet.rs#1164]
### Task description

Currently we are using manager.recoverAccounts with the following params: accountGapLimit = 10 and addressGapLimit = 0; and it is taking a considerably long time to return.

Please could we benchmark how long it takes for this? And is this parallelised?

### Requirements

- [ ] Benchmark time it takes to restore an single account and address
- [ ] See if this increases linearly?

### Acceptance criteria

TBD??

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [ ] I have linked the correct milestone and/or project

**Comment by Thoralf-M** [comment]
recoverAccounts:
| account gap limit | address gap limit | time |
| ------------------------- | ------------------------- | ------- |
| 1 | 1  | 14.022ms |
| 10 | 1  | 119.441ms |
| 20 | 1  | 241.537ms |
| 50 | 1  | 491.941ms |
| 100 | 1  | 865.182ms |
| 1  | 10  | 80.375ms |
| 10 | 10  | 585.506ms |
| 20 | 10  | 1.181s |
