### ISSUE TITLE
[Task]: Add method for rejecting an async transaction

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/wallet.rs#1197]
### Task description

In firefly we would like to be able to reject/return a transaction that was sent to us with async conditions (i.e. `Storage Deposit Return Unlock Condition` or `Expiration Unlock Condition`), without providing the storage deposit ourselves.

This means that we would just send the whole amount of a transaction back to the sender.

### Requirements

- [ ] Rejecting a basic output would send it back
- [ ] Reject native tokens would send them back?
- [ ] Rejecting an nft would send it back?

### Acceptance criteria

TBD

### Creation checklist

- [ ] I have assigned this task to the correct people
- [ ] I have added the most appropriate labels
- [ ] I have linked the correct milestone and/or project

**Comment by Tuditi** [comment]
The issue is a nice-to-have, but low priority at the moment!

**Comment by Thoralf-M** [comment]
For native tokens and NFTs it doesn't work, would only be possible for the base amount from a basic output.
Waiting for a decision if it's still required then
