### ISSUE TITLE
[Task]: Make output collection more granular

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/wallet.rs#941]
### Task description

Currently try_collect_outputs() tries to collect all basic outputs and can only be called during syncing.
This should change so it can be called manually and one should also be able to set what should be collected:
- nothing
- only micro transactions (amount with storage deposit return)
- native tokens
- nft outputs

### Requirements

- [ ] Expose try_collect_outputs()
- [ ] Add an optional parameter where one can define 
```
- only micro transactions (amount with storage deposit return)
- native tokens
- nft outputs
```
- [ ] Extract the part in try_collect_outputs(), which returns which outputs can be collected currently, into a separated function which returns `Vec<OutputData>` (or just `Vec<OutputId>`?) of the outputs, that can be collected

### Acceptance criteria

Requirements done

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
