### ISSUE TITLE
[Task]: Docs - Stardust Updates

### ISSUE THREAD

**Issue by charlesthompson3** [iotaledger/wallet.rs#963]
### Task description

With the upcoming stardust changes, some articles in the documentation may require updates and versioning.

And we need to be able to launch products with their respective docs to improve the overall developer experience.

### Requirements

The following pages may require updating. Please feel free to add or remove any items you see fit.

- [ ] Overview
  - [ ] Rust
    - [ ] Getting started
      - [ ] How to setup?
      - [ ] Examples
    - [ ] Guides
      -  [ ] Guide X
    - [ ] API Reference
  - [ ] Node.js
    - [ ] Getting started
      - [ ] How to setup?
      - [ ] Examples
    - [ ] Guides
      -  [ ] Guide X (excahnge)
    - [ ] API Reference
  - [ ] Java
    - [ ] Getting started
      - [ ] How to setup?
      - [ ] Examples
    - [ ] Guides
      -  [ ] Guide X
    - [ ] API Reference
  - [ ] Python
    - [ ] Getting started
      - [ ] How to setup?
      - [ ] Examples
    - [ ] Guides
      -  [ ] Guide X
    - [ ] API Reference
- [ ] Troubleshooting
- [ ] Contribute

A link to the parent issue can be found here: https://github.com/iotaledger/stardust-project/issues/45

**Comment by thibault-martinez** [comment]
Closed for https://github.com/iotaledger/wallet.rs/issues/1257, https://github.com/iotaledger/wallet.rs/issues/1258, https://github.com/iotaledger/wallet.rs/issues/1259 and https://github.com/iotaledger/iota-sdk/issues/108
